general:
  s3_regional_buckets: true
project:
  name: cfn-ps-sumo-logic-log-centralization
  shorten_stack_name: true
  regions:
    - us-east-1

tests:
  default:
    template: ./templates/main.template.yaml
    regions:
      - us-east-1
    parameters:
      QSS3KeyPrefix: "cfn-ps-sumo-logic-log-centralization/"
      QSS3BucketName: "tcat-cfn-ps-sumo-logic-log-centralization"
      QSS3BucketRegion: "us-east-1"
      QSVersion: "2"

      ## Sumo Logic configuration
      Section1aSumoLogicDeployment: "us1"
      Section1bSumoLogicAccessID: $[taskcat_ssm_/sumologic/Section1bSumoLogicAccessID] #required
      Section1cSumoLogicAccessKey: $[taskcat_ssm_/sumologic/Section1cSumoLogicAccessKey] #required
      Section1dSumoLogicOrganizationId: $[taskcat_ssm_/sumologic/Section1dSumoLogicOrganizationId] #required
      Section1eSumoLogicResourceRemoveOnDeleteStack: "true"

      #cloudtrail configuration

      Section2fCloudTrailCreateBucket: "Yes"
      # Section2gCloudTrailLogsBucketName: "" Required if Section2fCloudTrailCreateBucket is set to No
      Section2hCloudTrailCreateLogSource: "Yes"
      Section2iCloudTrailBucketPathExpression: "AWSLogs/*"
      Section2jCloudTrailLogsSourceCategoryName: "aws/quickstart/cloudtrail/logs"
      Section2aInstallCloudTrailApp: "Yes"
      Section2bInstallPCICloudTrailApp: "Yes"
      Section2cInstallCISFoundationApp: "Yes"
      Section2dInstallCloudTrailMonitoringAnalyticsApp: "Yes"
      Section2eInstallCloudTrailSecOpsApp: "Yes"

      # guarddduty configuration

      Section3aInstallGuardDutyApps: "Both"
      Section3bGuardDutyCreateHttpLogsSource: "Yes"
      Section3cGuardDutyHttpLogsSourceCategoryName: "aws/quickstart/guardduty/logs"

      # vpc configuration

      Section4aInstallVpcApps: "All"
      Section4bVpcCreateBucket: "Yes"
      # Section4cVpcLogsBucketName: "" Required when Section4bVpcCreateBucket is set to No
      Section4dVpcCreateS3Source: "Yes"
      Section4eVpcBucketPathExpression: "VPC-FLOW-LOGS/*"
      Section4fVpcLogsSourceCategoryName: "aws/quickstart/vpc/flow/logs"

      Section5aInstallThreatIntelApp: "Yes"
      Section5bElasticLoadBalancerSourceCategory: "*elb*"

      # s3 audit configuration

      Section6aInstallS3AuditApp: "Yes"
      Section6bS3AuditCreateBucket: "Yes"
      # Section6cS3AuditLogsBucketName: "" Required if Section6bS3AuditCreateBucket is set to No
      Section6dS3AuditCreateS3Source: "Yes"
      Section6eS3AuditBucketPathExpression: "S3-AUDIT-LOGS/*"
      Section6fS3AuditLogsSourceCategoryName: "aws/quickstart/s3/audit/logs"

      # security hub configuration

      Section7aInstallSecurityHubAuditApp: "Yes"
      Section7bEnableSecurityHub: "No"
      Section7cSecurityHubCreateBucket: "Yes"
      # Section7dSecurityHubLogsBucketName: "" Required if Section7cSecurityHubCreateBucket is set to No
      Section7eSecurityHubCreateS3Source: "Yes"
      Section7fSecurityHubBucketPathExpression: "*securityhub*/*"
      Section7gSecurityHubLogsSourceCategoryName: "aws/quickstart/securityhub/logs"

      # WAF configuration

      Section8aInstallWafApp: "Yes"
      Section8bWafCreateBucket: "Yes"
      # Section8cWafLogsBucketName: "" Required if Section8bWafCreateBucket is set to No
      Section8dWafCreateDeliveryStreamSource: "Yes"
      Section8eWafDeliveryStreamSourceCategoryName: "aws/quickstart/waf/logs"

      # config configuration

      Section9aInstallConfigApp: "Yes"
      Section9bConfigCreateBucket: "Yes"
      # Section9cConfigLogsBucketName: "" Required when Section9bConfigCreateBucket is set to No
      Section9dConfigCreateS3LogsSource: "Yes"
      Section9eConfigS3BucketLogsPathExpression: "AWSLogs/*/Config/*/*"      
      Section9fConfigS3LogsSourceCategoryName: "aws/quickstart/config/logs"

      # enable auto logging configuration
      Section10aEnableAutoLogging: "Skip"
      Section10bEnableLoggingForExistingResources: "No"
      Section10cS3LoggingBucketPrefix: "S3_AUDIT_LOGS/"
      Section10eVPCLoggingBucketPrefix: "VPC_LOGS/"
      Section11NFWLogsNFWBucketPrefix: "NFW/"
      Section10dS3LoggingFilterExpression: ""
      Section10fVPCLoggingFilterExpression: ""
      Section10FireWallLoggingFilterExpression: ""

      # network firewall configuration

      Section11NFWCreateS3Bucket: "Yes"
      Section11NFWCreateS3Source: "Yes"
      Section11InstallNFWApp: "Yes"
      Section11CreateNewFW: "No"
      # Section11VPCID: "" Required when Section11CreateNewFW is set to Yes
      # Section11SubnetID: "" Required when Section11CreateNewFW is set to Yes
      Section11CreateFirewallPolicy: "Yes"
      # Section11FirewallPolicyArn: "" Required when Section11CreateFirewallPolicy is set to No
      Section11StatefulRule: 'pass tcp 10.20.20.0/24 45400:45500 <> 10.10.10.0/24 5203 (msg:"test";sid:1;rev:1;)'
      Section11StatelessRule: "80"
      # Section11NFWLogsS3BucketName: "" Required when Section11NFWCreateS3Bucket is set to No
      Section11NFWS3BucketLogsPathExpression: "*AWSLogs/*/network-firewall/*"
      Section11NFWS3SourceCategoryName: "aws/quickstart/nfw/logs"
