AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Template to setup the common AWS and Sumo Logic resources for AWS Quick Start Solution. (qs-1ut5k8331)"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - SumoOrganizationId
          - RemoveSumoResourcesOnDeleteStack
          - SumoAccountID

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - CreateCollector
          - CollectorName

      - Label:
          default: "App Details - Configuration"
        Parameters:
          - CreateBucket
          - BucketName
          - CreateTrail

      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      SumoOrganizationId:
        default: "Sumo Logic Organization Id"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"
      SumoAccountID:
        default: "Sumo Logic AWS Account ID"

      CreateCollector:
        default: "Create Sumo Logic Collector"
      CollectorName:
        default: "Collector Name"

      CreateBucket:
        default: "Create AWS S3 Bucket"
      BucketName:
        default: "AWS S3 Bucket Name"
      CreateTrail:
        default: "Create Trail for the provided Bucket"

      QSS3BucketName:
        default: "Quick Start S3 bucket name"

      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  SumoOrganizationId:
    Description: "The Account Overview page displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description:
      "To delete collectors, sources and apps when the stack is deleted, set this parameter to true. Default is true.
      Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String
  SumoAccountID:
    Type: String
    Description: "Account belonging to Sumo Logic used for ingestion of logs from customers"
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic AWS Account ID can not be empty."
    Default: "926226587429"

  CreateCollector:
    Type: String
    Description:
      "Yes -> To Create Sumo Logic Collector in Sumo Logic for AWS Quick Start Solution.
      No -> Skip Installation of the collector."
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-QuickStart-Collector

  CreateBucket:
    Type: String
    Description: "Yes - Create a new bucket in AWS S3."
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  BucketName:
    Type: String
    Description: "New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
  CreateTrail:
    Type: String
    Description: "Yes - Create a trail for the provided S3 Bucket"
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-ia"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "cfn-ps-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"


Conditions:
  UsingDefaultBucket: !Or 
    - !Equals [!Ref QSS3BucketName, 'aws-ia']
    - !Equals [!Ref QSS3BucketName, 'sumologic-aws-security-solutions']
    - !Equals [!Ref QSS3BucketName, 'tcat-cfn-ps-sumo-logic-cloudsiem']

  install_collector: !Equals [!Ref CreateCollector, "Yes"]
  create_target_s3_bucket: !Equals [!Ref CreateBucket, "Yes"]

  create_cloudtrail: !And
    - !Condition create_target_s3_bucket
    - !Equals [!Ref CreateTrail, "Yes"]
  create_sns_topic: !Or
    - !Condition create_target_s3_bucket
    - !Condition install_collector

Resources:
  SumoLogicHelperRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudtrail:CreateTrail
                  - cloudtrail:DeleteTrail
                  - cloudtrail:UpdateTrail
                  - cloudtrail:StartLogging
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:PutBucketLogging
                  - s3:PutBucketAcl
                  - s3:GetBucketAcl
                  - ec2:DescribeVpcs
                  - ec2:DeleteFlowLogs
                  - ec2:CreateFlowLogs
                  - logs:CreateLogDelivery
                  - logs:DeleteLogDelivery
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*"
                  - !Sub "arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*"
                  - !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:*"
                  - !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}::*"
                  - !Sub "arn:${AWS::Partition}:s3:::*"
                  - !Sub "arn:${AWS::Partition}:config:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - config:DescribeConfigurationRecorderStatus
                  - config:DescribeConfigurationRecorders
                  - config:DeleteDeliveryChannel
                  - config:PutConfigurationRecorder
                  - config:DescribeDeliveryChannels
                  - config:StopConfigurationRecorder
                  - config:StartConfigurationRecorder
                  - config:PutDeliveryChannel
                  - config:DeleteConfigurationRecorder 
                Resource: '*'
              - Effect: Allow
                Action:
                  - securityhub:EnableSecurityHub
                  - securityhub:DisableSecurityHub
                Resource:
                  - !Sub arn:${AWS::Partition}:securityhub:*:${AWS::AccountId}:hub/default
                  - !Sub arn:${AWS::Partition}:securityhub:*:${AWS::AccountId}:/accounts
              - Effect: Allow
                Action: iam:PassRole
                Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*'
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - config.amazonaws.com
              - Sid: AllowCreateServiceLinkedRole
                Effect: Allow
                Action: iam:CreateServiceLinkedRole
                Condition:
                  StringLike:
                    iam:AWSServiceName:
                      - securityhub.amazonaws.com
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/securityhub.amazonaws.com/AWSServiceRoleForSecurityHub

  SumoLogicLambdaHelper:
    Type: "AWS::Serverless::Function"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Lambda functions should be deployed inside a VPC    
      cfn-lint:
        config:
          ignore_checks:
            - E3030 # Valid value for Runtime (python3.11)
    Properties:
      Handler: main.handler
      Runtime: python3.11
      CodeUri:
        Bucket: !Sub
          - "${S3Bucket}"
          - S3Bucket:
              !If [
                UsingDefaultBucket,
                !Sub "${QSS3BucketName}-${AWS::Region}",
                !Ref QSS3BucketName,
              ]
        Key: !Sub "${QSS3KeyPrefix}templates/apps/sumo-aws-apps/sumologic-app-utils/sumo_app_utils.zip"
      MemorySize: 128
      Timeout: 900
      DeadLetterQueue:
        TargetArn: !Ref AWS::NoValue
        Type: SQS
      ReservedConcurrentExecutions: 4
      VpcConfig:
        SecurityGroupIds:
          - !Ref AWS::NoValue
        SubnetIds:
          - !Ref AWS::NoValue
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

  SumoSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${SumoAccountID}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                Resource: 
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"
                  
  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_collector
    Properties:
      ServiceToken: !GetAtt SumoLogicLambdaHelper.Arn
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref CollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoSNSTopic:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W47
            reason: SNS Topic should specify KmsMasterKeyId property
    Condition: create_sns_topic
    Type: "AWS::SNS::Topic"
    Properties:
      KmsMasterKeyId: !Ref AWS::NoValue
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  SumoSNSpolicy:
    Condition: create_sns_topic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
          - Action:
              - sns:Publish
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:s3:*:*:*"
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Resource:
              - !Ref SumoSNSTopic
      Topics:
        - Ref: SumoSNSTopic

  TargetS3Bucket:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W51
            reason: S3 bucket should likely have a bucket policy
          - id: W41
            reason: S3 Bucket should have encryption option set  
    Condition: create_target_s3_bucket
    Type: AWS::S3::Bucket
    DependsOn:
      - SumoSNSpolicy
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref SumoSNSTopic
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref AWS::NoValue
        LogFilePrefix: !Ref AWS::NoValue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  SumoCloudTrailExportPolicy:
    Condition: create_cloudtrail
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          - Sid: AWSBucketPermissionsAclCheck
            Effect: Allow
            Principal:
              Service: 
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSBucketExistenceCheck
            Effect: Allow
            Principal:
              Service: 
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:ListBucket
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: 
                - delivery.logs.amazonaws.com
                - config.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"

    DependsOn:
      - TargetS3Bucket

  SumoCloudTrail:
    Condition: create_cloudtrail
    Type: Custom::AWSTrail
    DependsOn:
      - SumoCloudTrailExportPolicy
    Properties:
      ServiceToken: !GetAtt SumoLogicLambdaHelper.Arn
      IsLogging: true
      IsMultiRegionTrail: false
      S3BucketName: !Ref BucketName
      TrailName: !Sub "SumoCloudTrail-${AWS::StackName}"

Outputs:
  StackName:
    Description: "Stack Name"
    Value: !Ref "AWS::StackName"
  SumoLogicLambdaHelperARN:
    Description: "Sumo Logic Lambda Helper ARN"
    Value: !GetAtt SumoLogicLambdaHelper.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SumoLogicHelperFunctionARN"
  SumoSourceRoleARN:
    Description: "Sumo Logic Source Role ARN"
    Value: !GetAtt SumoSourceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SumoSourceRoleARN"
  SumoCollectorID:
    Description: "Sumo Logic Collector ID"
    Condition: install_collector
    Value: !GetAtt SumoHostedCollector.COLLECTOR_ID
    Export:
      Name: !Sub "${AWS::StackName}-CollectorID"
  SNSTopicArn:
    Description: "SNS Topic ARN"
    Condition: create_sns_topic
    Value: !Ref SumoSNSTopic
    Export:
      Name: !Sub "${AWS::StackName}-SNSTopicArn"
  BucketName:
    Description: "BucketName"
    Value: !Ref BucketName
