// Edit this placeholder text as necessary to describe the deployment options.

This Partner Solution provides one deployment option.

* https://fwd.aws/Nm69g[Deploy {partner-product-name}^]. You build a new AWS environment that consists of the infrastructure resources required to provision applications to your Sumo Logic account and the necessary resources to your AWS account. During the deployment, you can choose which applications to install.

=== Scenarios supported by this Partner Solution

This Partner Solution supports the following scenarios:

* **Scenario 1: You do not use AWS security services or Sumo Logic.** You did not
configure AWS to use one or more security services listed under <<Specialized knowledge>>,
but you want to collect and analyze data using Sumo Logic apps. For this scenario, use
this Partner Solution to set up AWS security services and configure Sumo Logic.

* **Scenario 2: You use AWS security services but not Sumo Logic.** You use the AWS security services listed under <<Specialized knowledge>> but have not configured Sumo
Logic to collect data from AWS or installed the corresponding Sumo Logic apps. For this
scenario, configure the auxiliary AWS services and resources to send data to Sumo
Logic. This scenario also installs the corresponding Sumo Logic apps.

* **Scenario 3: You use AWS security services and Sumo Logic.** You use the AWS
security services listed under <<Specialized knowledge>> and you collect and analyze data
from one or more of them in Sumo Logic. For this scenario, configure the auxiliary AWS
services and resources to send data to Sumo Logic. This scenario is intended only for
nonconfigured AWS security services and their corresponding Sumo Logic apps.
