This guide covers the information you need to deploy the {partner-product-name} Partner Solution in the AWS Cloud.

// Fill in the info in <angle brackets> for use on the landing page only:
This Amazon Web Services (AWS) Partner Solution automatically deploys Sumo Logic Security Integrations on the AWS Cloud. It's for people who want to configure the Sumo Logic console for 12 AWS services that provide security analytics for a single AWS account. With the default settings, this Partner Solution deploys CloudTrail and GuardDuty apps.

== Sumo Logic Security Integrations on AWS

Sumo Logic is focused on continuous intelligence, a category of software that addresses data challenges presented by digital transformations, modern applications, and cloud computing. The Sumo Logic Continuous Intelligence Platform automates the collection, ingestion, and analysis of applications, infrastructure, security, and Internet of Things (IoT) data to derive actionable insights.

This Partner Solution uses Sumo Logic https://assets-www.sumologic.com/resources/brief/Cloud_SIEM_Powered_by_AWS.pdf[Cloud SIEM (security information and incident management) powered by AWS^]. Sumo Logic Cloud SIEM uses apps to collect security events generated by AWS and other security services to provide an aggregate view of overall security and compliance posture.

Sumo Logic has apps for each AWS security service (for example, the Sumo Logic app for AWS CloudTrail) and apps that support multiple AWS services (for example, Threat Intel for AWS). Sumo Logic customers can track user activity, monitor threats, and understand how their
security posture compares with global benchmarks. Sumo Logic also uses apps to audit and help maintain compliance with the
Payment Card Industry (PCI) Data Security Standard (DSS) and Center for Internet
Security (CIS).

The included template automatically creates resources that use various AWS services to collect logs, which are sent to your preregistered Sumo Logic account.

NOTE: Deploying this solution does not guarantee an organization’s compliance with any laws, certifications, policies, or other regulations.

// For advanced information about the product, troubleshooting, or additional functionality, refer to the https://{partner-solution-github-org}.github.io/{partner-solution-project-name}/operational/index.html[Operational Guide^].

// For information about using this Partner Solution for migrations, refer to the https://{partner-solution-github-org}.github.io/{partner-solution-project-name}/migration/index.html[Migration Guide^].