AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Template to setup the Amazon S3 Audit app with AWS and Sumo Logic resources for AWS Quick Start Solution. (qs-1ut5kb3n8)"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - SumoOrganizationId
          - RemoveSumoResourcesOnDeleteStack
          - SumoAccountID
      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - InstallApp
          - CollectorName

      - Label:
          default: "App Details - S3 Audit Source Configuration"
        Parameters:
          - CreateS3Bucket
          - LogsS3BucketName
          - CreateS3AuditSource
          - S3BucketLogsPathExpression
          - S3AuditSourceName
          - S3AuditSourceCategoryName

      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      SumoOrganizationId:
        default: "Sumo Logic Organization Id"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"
      SumoAccountID:
        default: "Sumo Logic AWS Account ID"

      InstallApp:
        default: "Install Sumo Logic App"
      CollectorName:
        default: "Collector Name"

      CreateS3Bucket:
        default: "Create AWS S3 Bucket"
      LogsS3BucketName:
        default: "AWS S3 Bucket Name"
      CreateS3AuditSource:
        default: "Create Sumo Logic Amazon S3 Audit Logs Source"
      S3BucketLogsPathExpression:
        default: "Path Expression for the logs"
      S3AuditSourceName:
        default: "Sumo Logic Amazon S3 Audit Logs Source Name"
      S3AuditSourceCategoryName:
        default: "Sumo Logic Amazon S3 Audit Logs Source Category Name"

      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

      ParentStackName:
        default: "If Any, Name of parent Stack"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  SumoOrganizationId:
    Description: "The Account Overview page displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description:
      "To delete collectors, sources and apps when the stack is deleted, set this parameter to true. Default is true.
      Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String
  SumoAccountID:
    Type: String
    Description: "Account belonging to Sumo Logic used for ingestion of logs from customers"
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic AWS Account ID can not be empty."
    Default: "926226587429"

  InstallApp:
    Type: String
    Description:
      "Yes -> To Install Sumo Logic App in Sumo Logic for AWS Quick Start Solution.
      No -> Skip Installation of the app."
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-S3-Audit-Collector

  CreateS3Bucket:
    Type: String
    Description: "Yes - Create a new S3 bucket in AWS S3.
      No - Use an existing S3 bucket from AWS S3 which has S3 Audit Logs."
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  LogsS3BucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.
      New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
  CreateS3AuditSource:
    Type: String
    Description:
      "Yes - to create Sumo Logic Amazon S3 Audit Log Source with provided bucket Name.
      No - to skip creation of the Sumo Logic Amazon S3 Audit Log Source."
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  S3BucketLogsPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "S3-AUDIT-LOGS/*"
  S3AuditSourceName:
    Type: String
    Description: Change the Sumo Logic Amazon S3 Audit Source name to be created else default name will be used.
    Default: AWS-S3-Audit-Source
  S3AuditSourceCategoryName:
    Type: String
    Description:
      "Existing - Change to an existing Source Category from Sumo Logic if Amazon S3 Source is not created.
      New - Default will be used if Amazon S3 Source is Created."
    Default: AWS/S3/Audit/Logs

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-ia"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "cfn-ps-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.

Conditions:
  do_not_use_parent_stack: !Equals [!Ref ParentStackName, "ParentStackName"]
  UsingDefaultBucket: !Or 
    - !Equals [!Ref QSS3BucketName, 'aws-ia']
    - !Equals [!Ref QSS3BucketName, 'sumologic-aws-security-solutions']
    - !Equals [!Ref QSS3BucketName, 'tcat-cfn-ps-sumo-logic-cloudsiem']

  install_app: !Equals [!Ref InstallApp, "Yes"]
  create_target_s3_bucket: !And
    - !Equals [!Ref CreateS3Bucket, "Yes"]
    - !Condition create_sns_topic
  install_s3_audit_source: !Equals [!Ref CreateS3AuditSource, "Yes"]
  create_validation_logs_s3_bucket: !And
    - !Condition do_not_use_parent_stack
    - !Equals [!Ref CreateS3Bucket, "No"]
    - !Equals [!Ref CreateS3AuditSource, "Yes"]
  s3audit_validation_path_expression: !And
    - !Condition do_not_use_parent_stack
    - !Equals [!Ref CreateS3AuditSource, "Yes"]
  create_sns_topic: !And
    - !Condition do_not_use_parent_stack
    - !Condition install_s3_audit_source

Resources:
  SumoLogicHelperRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: IAM role should not allow * resource on its permissions policy
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                Resource: "*"

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:*
                  - !Sub arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:*:log-stream:*

              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:PutBucketLogging
                  - s3:PutBucketAcl
                  - s3:GetBucketAcl
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::*

  SumoLogicHelperFunction:
    Type: "AWS::Serverless::Function"
    Condition: do_not_use_parent_stack
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Lambda functions should be deployed inside a VPC    
      cfn-lint:
        config:
          ignore_checks:
            - E3030 # Valid value for Runtime (python3.11)
    Properties:
      Handler: main.handler
      Runtime: python3.11
      CodeUri:
        Bucket: !Sub
          - "${S3Bucket}"
          - S3Bucket:
              !If [
                UsingDefaultBucket,
                !Sub "${QSS3BucketName}-${AWS::Region}",
                !Ref QSS3BucketName,
              ]
        Key: !Sub "${QSS3KeyPrefix}templates/apps/sumo-aws-apps/sumologic-app-utils/sumo_app_utils.zip"
      MemorySize: 128
      Timeout: 900
      DeadLetterQueue:
        TargetArn: !Ref AWS::NoValue
        Type: SQS
      ReservedConcurrentExecutions: 4
      VpcConfig:
        SecurityGroupIds:
          - !Ref AWS::NoValue
        SubnetIds:
          - !Ref AWS::NoValue
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

  ValidationLogsS3BucketBucket:
    Condition: create_validation_logs_s3_bucket
    Type: Custom::AWSValidation
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      PARAMETER_NAME: "LogsS3BucketName"
      PARAMETER_VALUE: !Ref LogsS3BucketName
      PARAMETER_ALLOWED_PATTERN: '(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'

  ValidationS3AuditPathExpression:
    Condition: s3audit_validation_path_expression
    Type: Custom::AWSValidation
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      PARAMETER_NAME: "S3 Audit bucket path expression (S3BucketLogsPathExpression)"
      PARAMETER_VALUE: !Ref S3BucketLogsPathExpression
      PARAMETER_ALLOWED_PATTERN: '.+'

  SumoRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${SumoAccountID}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${LogsS3BucketName}"
                  - !Sub "arn:${AWS::Partition}:s3:::${LogsS3BucketName}/*"

  SumoSNSTopic:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W47
            reason: SNS Topic should specify KmsMasterKeyId property  
    Condition: create_sns_topic
    Type: "AWS::SNS::Topic"
    Properties:
      KmsMasterKeyId: !Ref AWS::NoValue
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  SumoSNSSubscription:
    Condition: install_s3_audit_source
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !If
        - create_sns_topic
        - !Ref SumoSNSTopic
        - !ImportValue
          "Fn::Sub": "${ParentStackName}-SNSTopicArn"
      Endpoint: !GetAtt SumoS3AuditSource.SUMO_ENDPOINT
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential

  SumoSNSpolicy:
    Condition: create_sns_topic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
          - Action:
              - sns:Publish
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:s3:::${LogsS3BucketName}"
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Resource:
              - !Ref SumoSNSTopic
      Topics:
        - Ref: SumoSNSTopic

  TargetS3Bucket:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W51
            reason: S3 bucket should likely have a bucket policy
          - id: W41
            reason: S3 Bucket should have encryption option set  
    Condition: create_target_s3_bucket
    Type: AWS::S3::Bucket
    DependsOn:
      - SumoSNSpolicy
    Properties:
      BucketName: !Ref LogsS3BucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref SumoSNSTopic
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref AWS::NoValue
        LogFilePrefix: !Ref AWS::NoValue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_s3_audit_source
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          "Fn::Sub": "${ParentStackName}-SumoLogicHelperFunctionARN"
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack:
        !If [
          do_not_use_parent_stack,
          !Ref RemoveSumoResourcesOnDeleteStack,
          false,
        ]
      CollectorName: !Ref CollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoS3AuditSource:
    Type: Custom::AWSSource
    Condition: install_s3_audit_source
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          "Fn::Sub": "${ParentStackName}-SumoLogicHelperFunctionARN"
      SourceType: AwsS3AuditBucket
      Region: !Ref "AWS::Region"
      SourceName: !Ref S3AuditSourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref S3AuditSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      TargetBucketName: !Ref LogsS3BucketName
      PathExpression: !Ref S3BucketLogsPathExpression
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          "Fn::Sub": "${ParentStackName}-SumoSourceRoleARN"

  SumoAmazonS3AuditApp:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          "Fn::Sub": "${ParentStackName}-SumoLogicHelperFunctionARN"
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart - Amazon S3 Audit"
      AppId: "cf3ba421-d959-4b08-9ae8-5bd4202eea87"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        s3datasrc: !Sub "_sourceCategory=${S3AuditSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

Outputs:
  QSS3BucketName:
    Description: Quick Start S3 bucket name
    Value: !Ref QSS3BucketName
  SumoRoleArn:
    Description: ARN of the cretaed Role.
    Condition: do_not_use_parent_stack
    Value: !GetAtt SumoRole.Arn

  SumoEndpoint:
    Description: SNS Subscription Endpoint
    Condition: install_s3_audit_source
    Value: !GetAtt SumoS3AuditSource.SUMO_ENDPOINT
